			<option value='AF'>AFGANISTAN</option>
			<option value='AL'>ALBANIA</option>
			<option value='DE'>ALEMANIA</option>
			<option value='AD'>ANDORRA</option>
			<option value='AO'>ANGOLA</option>
			<option value='AQ'>ANTARTIDA</option>
			<option value='AG'>ANTIGUA Y BARBUDA</option>
			<option value='AN'>ANTILLAS DE LOS PAISES BAJOS</option>
			<option value='SA'>ARABIA SAUDITA</option>
			<option value='DZ'>ARGELIA</option>
			<option value='AR'>ARGENTINA</option>
			<option value='AM'>ARMENIA</option>
			<option value='AW'>ARUBA</option>
			<option value='AU'>AUSTRALIA</option>
			<option value='AT'>AUSTRIA</option>
			<option value='AZ'>AZERBAIJN</option>
			<option value='BS'>BAHAMAS</option>
			<option value='BH'>BAHRAYN</option>
			<option value='BD'>BANGLADESH</option>
			<option value='BB'>BARBADOS -ISLAS DE BARLOVENTO-</option>
			<option value='BY'>BELARUS</option>
			<option value='BE'>BELGICA</option>
			<option value='BZ'>BELICE</option>
			<option value='BJ'>BENN</option>
			<option value='BM'>BERMUDAS</option>
			<option value='MM'>BIRMANIA</option>
			<option value='BO'>BOLIVIA</option>
			<option value='BA'>BOSNIA Y HERZEGOVINA</option>
			<option value='BW'>BOTSWANA ESTADO DE  AFRICA AUSTRAL</option>
			<option value='BV'>BOUVET ISLA NORUETA DEL ATLANTICO SUR</option>
			<option value='BR'>BRASIL</option>
			<option value='BN'>BRUNEI DARUSSALAM</option>
			<option value='BG'>BULGARIA</option>
			<option value='BF'>BURKINA FASO</option>
			<option value='BI'>BURUNDI</option>
			<option value='BT'>BUTN</option>
			<option value='KH'>CAMBOYA</option>
			<option value='CM'>CAMERN</option>
			<option value='CA'>CANADA</option>
			<option value='CV'>CAPE VERDE</option>
			<option value='TD'>CHAD</option>
			<option value='CL'>CHILE</option>
			<option value='CN'>CHINA</option>
			<option value='CY'>CHIPRE</option>
			<option value='CO'>COLOMBIA</option>
			<option value='KM'>COMORES</option>
			<option value='CG'>CONGO</option>
			<option value='CR'>COSTA RICA</option>
            <option value='CRLTF'>COSTA RICA (LATIN FREIGHT)</option>
			<option value='HR'>CROACIA</option>
			<option value='CU'>CUBA</option>
			<option value='DK'>DINAMARCA</option>
			<option value='DJ'>DJIBOUTI</option>
			<option value='DM'>DOMINICA</option>
			<option value='EC'>ECUADOR</option>
			<option value='EG'>EGYPTO</option>
			<option value='SV'>EL SALVADOR</option>
            <option value='SVLTF'>EL SALVADOR (LATIN FREIGHT)</option>
			<option value='VA'>EL VATICANO</option>
			<option value='AE'>EMIRATOS RABES UNIDOS</option>
			<option value='ER'>ERITREA</option>
			<option value='SK'>ESLOVAQUIA</option>
			<option value='SI'>ESLOVENIA</option>
			<option value='ES'>ESPA—A</option>
			<option value='LV'>ESTADO RUSO DE LATVIA</option>
			<option value='US'>ESTADOS UNIDOS</option>
			<option value='EE'>ESTONIA</option>
			<option value='ET'>ETIOPA</option>
			<option value='RU'>FEDERACIN RUSIA</option>
			<option value='FJ'>FIDJI</option>
			<option value='PH'>FILIPINAS</option>
			<option value='FI'>FINLANDIA</option>
			<option value='FR'>FRANCIA</option>
			<option value='GA'>GABN</option>
			<option value='GM'>GAMBIA</option>
			<option value='GE'>GEORGIA</option>
			<option value='GS'>GEORGIA DEL SUR Y LAS ISLAS DEL SUR DE SANDWICH</option>
			<option value='GH'>GHNA</option>
			<option value='GI'>GIBRALTAR</option>
			<option value='GD'>GRANADA</option>
			<option value='GR'>GRECIA</option>
			<option value='GL'>GROENLANDIA</option>
			<option value='GP'>GUADALUPE</option>
			<option value='GU'>GUAM</option>
			<option value='GT'>GUATEMALA</option>
            <option value='GTLTF'>GUATEMALA (LATIN FREIGHT)</option>
			<option value='GN'>GUINEA</option>
			<option value='GQ'>GUINEA ECUATORIAL</option>
			<option value='GF'>GUINEA FRANCESA</option>
			<option value='GW'>GUINEA PORTUGUESA</option>
			<option value='GY'>GUYANA</option>
			<option value='HT'>HAIT</option>
			<option value='HN'>HONDURAS-SPS</option>
            <option value='HN1'>HONDURAS-TGU</option>
            <option value='HN2'>HONDURAS-SPS/TGU</option>
            <option value='HNLTF'>HONDURAS (LATIN FREIGHT)</option>
			<option value='HK'>HONG KONG</option>
			<option value='HU'>HUNGRIA</option>
			<option value='IN'>INDIA</option>
			<option value='IO'>INDIAS BRITANICAS TERRITORIO DEL OCENO INDICO</option>
			<option value='ID'>INDONESIA</option>
			<option value='IR'>IRAN</option>
			<option value='IQ'>IRAQ</option>
			<option value='IE'>IRLANDIA</option>
			<option value='MQ'>ISLA DE MARTINICA</option>
			<option value='CX'>ISLA DE NAVIDAD</option>
			<option value='MU'>ISLA MAURICIO</option>
			<option value='NF'>ISLA NORFOLK</option>
			<option value='PN'>ISLA PITCAIRN</option>
			<option value='IS'>ISLANDIA</option>
			<option value='VG'>ISLAS BRITNICAS VIRGINIA</option>
			<option value='KY'>ISLAS CAYMAN</option>
			<option value='CK'>ISLAS DE COOK</option>
			<option value='VI'>ISLAS DE ESTADOS UNIDOS VIRGINIA</option>
			<option value='FK'>ISLAS DE FALKAND MALVINAS</option>
			<option value='FO'>ISLAS DE FAROE</option>
			<option value='CC'>ISLAS DE LOS COCOS</option>
			<option value='MP'>ISLAS MARIANAS DEL NORTE</option>
			<option value='MH'>ISLAS MARSHALL</option>
			<option value='UM'>ISLAS MENORES Y PERFERICAS DE ESTADOS UNIDOS</option>
			<option value='SB'>ISLAS SALOMON</option>
			<option value='TC'>ISLAS TURCAS Y TURCOS</option>
			<option value='IL'>ISRAEL</option>
			<option value='IT'>ITALIA</option>
			<option value='JM'>JAMAICA</option>
			<option value='JP'>JAPÛN</option>
			<option value='JO'>JORDANIA</option>
			<option value='KZ'>KASAJISTN</option>
			<option value='KE'>KENYA</option>
			<option value='KG'>KIRGUIZISTN</option>
			<option value='KI'>KIRIBATI</option>
            <option value='KR'>KOREA</option>
			<option value='KW'>KUWAIT</option>
			<option value='LA'>LAOS</option>
			<option value='LS'>LESOTHO O BASUTOLANDIA</option>
			<option value='LB'>LBANO</option>
			<option value='LR'>LIBERIA</option>
			<option value='LY'>LIBIA ARABE JAMAHIRYA</option>
			<option value='LI'>LIECHTENSTEIN</option>
			<option value='LT'>LITUNIA</option>
			<option value='LU'>LUXEMBURGO</option>
			<option value='MO'>MACAO</option>
			<option value='MK'>MACEDONIA, ANTIGUA REPBLICA DE YUGOESLAVIA</option>
			<option value='MG'>MADAGASCAR</option>
			<option value='MY'>MALASYA</option>
			<option value='MW'>MALAWI</option>
			<option value='MV'>MALDIVAS</option>
			<option value='ML'>MAL</option>
			<option value='MT'>MALTA</option>
			<option value='MA'>MARRUECOS</option>
			<option value='MR'>MAURITANIA</option>
			<option value='YT'>MAYOTT</option>
			<option value='MX'>MEXICO</option>
            <option value='MXLTF'>MEXICO (LATIN FREIGHT)</option>
			<option value='MC'>MNACO</option>
			<option value='MN'>MONGOLIA</option>
			<option value='MS'>MONTSERRAT</option>
			<option value='MZ'>MOZAMBIQUE</option>
			<option value='NA'>NAMIBIA</option>
			<option value='NR'>NAURU</option>
			<option value='NP'>NEPAL</option>
			<option value='NI'>NICARAGUA</option>
			<option value='N1'>NICARAGUA (GRH)</option>
            <option value='NILTF'>NICARAGUA (LATIN FREIGHT)</option>
			<option value='NE'>NGER</option>
			<option value='NG'>NIGERIA</option>
			<option value='NO'>NORUEGA</option>
			<option value='NC'>NUEVA CALEDONIA</option>
			<option value='PG'>NUEVA GUINEA - PAPUASIA</option>
			<option value='NZ'>NUEVA ZELANDA</option>
			<option value='OM'>OMN</option>
			<option value='NL'>PAISES BAJOS - HOLANDA</option>
			<option value='PK'>PAKISTAN</option>
			<option value='PW'>PALAOS</option>
			<option value='PS'>PALESTINA</option>
			<option value='PA'>PANAMA</option>
            <option value='PALTF'>PANAMA (LATIN FREIGHT)</option>
			<option value='PY'>PARAGUAY</option>
			<option value='PE'>PERU</option>
			<option value='PF'>POLINESIA FRANCESA</option>
			<option value='PL'>POLONIA</option>
			<option value='PT'>PORTUGAL</option>
			<option value='PR'>PUERTO RICO</option>
			<option value='QA'>QATAR</option>
			<option value='GB'>REINO UNIDO</option>
			<option value='SY'>REPUBLICA ARABE DE SIRIA</option>
			<option value='CZ'>REPUBLICA CHECA</option>
			<option value='CF'>REPUBLICA DE AFRICA CENTRAL</option>
			<option value='MD'>REPUBLICA DE MOLDOVIA</option>
			<option value='CD'>REPUBLICA DEMOCRTICA DEL CONGO</option>
			<option value='DO'>REPUBLICA DOMINICANA</option>
			<option value='TZ'>REPUBLICA UNIDA DE TANZANIA</option>
			<option value='KP'>REPUBLICAS DEMOCRTICAS DE COREA</option>
			<option value='RE'>RUNION</option>
			<option value='RW'>RUANDA</option>
			<option value='RO'>RUMANIA</option>
			<option value='EH'>SAHARA OCCIDENTAL</option>
			<option value='WS'>SAMOA</option>
			<option value='SM'>SAN MARINO</option>
			<option value='VC'>SAN VICENTE Y LAS GRANADINAS</option>
			<option value='SH'>SANTA HELENA</option>
			<option value='KN'>SANTA KITTS Y NEVIS </option>
			<option value='LC'>SANTA LUCIA</option>
			<option value='PM'>SANTO PIER Y MIKELON</option>
			<option value='NU'>SAVAGE ISLA DEL PACFICO</option>
			<option value='SN'>SENEGAL</option>
			<option value='CS'>SERBIA Y MONTENEGRO</option>
			<option value='SC'>SEYCHELLES</option>
			<option value='SL'>SIERRA LEONA</option>
			<option value='SG'>SINGAPUR</option>
			<option value='SO'>SOMALIA</option>
			<option value='LK'>SRI LANKA</option>
			<option value='SD'>SUDAN</option>
			<option value='SE'>SUECIA</option>
			<option value='CH'>SUIZA</option>
			<option value='ZA'>SUR AFRICA</option>
			<option value='SR'>SURINAM</option>
			<option value='SJ'>SVALBARD Y ENERO MAYEN</option>
			<option value='SZ'>SWAZILANDIA</option>
			<option value='TH'>TAILANDIA</option>
			<option value='TW'>TAIWAN PROVINCIA DE CHINA</option>
			<option value='TJ'>TAJIKISTAN</option>
			<option value='TL'>TIMOR-LESTE</option>
			<option value='TG'>TOGO</option>
			<option value='TK'>TOKELAU</option>
			<option value='ST'>TOMO DE SAO Y PRINCIPE</option>
			<option value='TO'>TONGA</option>
			<option value='TT'>TRINIDAD Y TOBAGO</option>
			<option value='TN'>TUNISIA</option>
			<option value='TR'>TURQUIA</option>
			<option value='TM'>TURKMENISTN</option>
			<option value='TV'>TUVALU</option>
			<option value='UA'>UCRANIA</option>
			<option value='UG'>UGANDA</option>
			<option value='UK'>GRAN BRETANA</option>
            <option value='UY'>URUGUAY</option>
			<option value='UZ'>UZBEKISTN</option>
			<option value='VU'>VANUATU</option>
			<option value='VE'>VENEZUELA</option>
			<option value='VN'>VIETNAM</option>
			<option value='WF'>WALLIS Y FUTUNA</option>
			<option value='YE'>YEMEN</option>
			<option value='ZM'>ZAMBIA</option>
			<option value='ZW'>ZIMBABWE</option>
			<option value='X1'>PAISES VARIOS</option>
